# Generated by Django 4.1.5 on 2023-01-13 04:40

from django.db import migrations, models
import resource_manager_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ("resource_manager_app", "0003_alter_technician_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="code",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[resource_manager_app.utils.letter_number_only_validator],
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="id_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
